{   'name': 'Library Management System',
    'author': 'Mohamed Tlig Kraini',
    'depends': ['base','contacts','mail'],
    'application': True,
    'sequence': 10,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'data/mail_penalty_template.xml',
        'data/mail_membership_terminated.xml',
        'data/sequence.xml',
        'views/menu.xml',
        'views/books.xml',
        'views/author.xml',
        'views/member.xml',
        'views/library_config_settings_views.xml',
        'views/borrow_book.xml',
        'views/membership.xml',
        'report/book_report.xml',
    ],
}